// In this file you can specify the trial data for your experiment


const trial_info = {
    key_press: [
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/7_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/7_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/8_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/8_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/9_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/9_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/10_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/10_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/11_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/11_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/12_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/12_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/13_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/13_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/12_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/12_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/11_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/11_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/10_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/10_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/9_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/9_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/8_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/8_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/7_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/7_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/6_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/6_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/5_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/5_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/4_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/4_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/3_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/3_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/2_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/2_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/1_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/1_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/13_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/13_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/14_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/14_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/15_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/15_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/14_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/14_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/15_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/15_50_same.jpg",
          angle: 50,
        },

    ]
};

const preparation_info = {
    preparation: [
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/1_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/1_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/2_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/2_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/3_50_different.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/3_50_same.jpg",
          angle: 50,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/4_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/4_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/5_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/5_150_same.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'different',
          picture: "mental_rotation_images/6_150_different.jpg",
          angle: 150,
        },
        {
          question: "Are these two figures the same except for their orientation?",
          key1: 'y',
          key2: 'm',
          y: 'same',
          m: 'different',
          expected: 'same',
          picture: "mental_rotation_images/6_150_same.jpg",
          angle: 150,
        },

    ]
};
